config/routes.rb
Rails.application.routes.draw do
  scope ':lang', constraints: Iqvoc.routing_constraint do
    resources :labels

    post 'labels/versions/:origin/branch' => 'labels/versions#branch', :as => 'label_versions_branch'
    post 'labels/versions/:origin/merge' => 'labels/versions#merge', :as => 'label_versions_merge'
    post 'labels/versions/:origin/to_review' => 'labels/versions#to_review', :as => 'label_versions_to_review'
    get 'labels/versions/:origin/consistency_check' => 'labels/versions#consistency_check', :as => 'label_versions_consistency_check'
    get 'labels/:origin/duplicate' => 'labels#duplicate', :as => 'label_duplicate'
    get 'label_dashboard' => 'xl_dashboard#label_index', as: 'label_dashboard'
    get 'concept_new_label' => 'labels#new_from_concept', as: 'concept_new_label'
    post 'concept_create_label' => 'labels#create_from_concept', as: 'concept_create_label'
  end
end

app/models/label/relation/base.rb
class Label::Relation::Base < ApplicationRecord
  class_attribute :rdf_namespace, :rdf_predicate
  self.rdf_namespace = nil
  self.rdf_predicate = nil

  self.table_name ='label_relations'

  belongs_to :domain, class_name: 'Label::Base'
  belongs_to :range,  class_name: 'Label::Base'

  def self.by_domain(domain)
    where(domain_id: domain)
  end

  def self.by_range(range)
    where(range_id: range)
  end

  def self.by_range_origin(origin)
    includes(:range).references(:labels).merge(Label::Base.by_origin(origin))
  end

  def self.range_editor_selectable
    # includes(:range) & Iqvoc::Xllabel.base_class.editor_selectable
    # Doesn't work correctly (kills label_relations.type condition :-( )
    includes(:range).
    where('labels.published_at IS NOT NULL OR (labels.published_at IS NULL AND labels.published_version_id IS NULL) ')
  end

  def self.range_in_edit_mode
    joins(:range).references(:labels).merge(Iqvoc::Xllabel.base_class.unpublished)
  end

  def self.view_section(obj)
    'relations'
  end

  def self.view_section_sort_key(obj)
    100
  end

  def self.partial_name(obj)
    'partials/label/relation/base'
  end

  def self.edit_partial_name(obj)
    'partials/label/relation/edit_base'
  end

  def self.bidirectional?
    false
  end
end

app/models/label/relation/bidirectional_relation_extension.rb
# encoding: UTF-8

# Copyright 2011-2016 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module Label
  module Relation
    module BidirectionalRelationExtension
      def create_with_bidirectional_relation(target_label, attributes = {})
        relation_class = proxy_association.reflection.class_name.constantize
        ActiveRecord::Base.transaction do
          # The one direction
          scope = relation_class.where(domain_id: proxy_association.owner.id, range_id: target_label.id)
          scope.any? || scope.create!(attributes)

          # The bidirectional direction
          scope = relation_class.where(domain_id: target_label.id, range_id: proxy_association.owner.id)
          scope.any? || scope.create!(attributes)
        end
      end

      def destroy_with_bidirectional_relation(target_label)
        relation_class = proxy_association.reflection.class_name.constantize
        ActiveRecord::Base.transaction do
          relation_class.where(domain_id: proxy_association.owner.id, range_id: target_label.id).load.each do |relation|
            relation.destroy
          end

          relation_class.where(domain_id: target_label.id, range_id: proxy_association.owner.id).load.each do |relation|
            relation.destroy
          end
        end
      end
    end
  end
end

app/models/label/relation/skosxl/base.rb
class Label::Relation::Skosxl::Base < Label::Relation::Base
  self.rdf_namespace = 'skosxl'

  def self.build_from_rdf(subject, predicate, object)
    create(domain: subject, range: object)
  end

  def build_rdf(document, subject)
    pred = self.class == Label::Relation::Skosxl::Base ? :labelRelation : self.rdf_predicate
    raise "Match::Skos::Base#build_rdf: Class #{self.class.name} needs to define self.rdf_namespace and self.rdf_predicate." unless pred

    subject.send(self.rdf_namespace.camelcase).send(pred, IqRdf.build_uri(range.origin))
  end
end

app/models/label/skosxl/properties/literal_form.rb
class Label::Skosxl::Properties::LiteralForm
  class_attribute :rdf_namespace, :rdf_predicate
  self.rdf_namespace = 'skosxl'
  self.rdf_predicate = 'literalForm'

  def self.build_from_rdf(rdf_subject, rdf_predicate, rdf_object)
    unless rdf_object =~ RdfApi::LITERAL_REGEXP
      raise InvalidStringLiteralError,
        "#{self.name}#build_from_rdf: Object (#{rdf_object}) must be a string literal"
    end

    lang = $3
    value = begin
      JSON.parse(%Q{["#{$1}"]})[0].gsub('\\n', "\n") # Trick to decode \uHHHHH chars
    rescue JSON::ParserError
      $1
    end

    rdf_subject.update(value: value, language: lang)
  end
end

app/controllers/labels/versions_controller.rb
class Labels::VersionsController < ApplicationController
  def merge
    current_label = Iqvoc::Xllabel.base_class.by_origin(params[:origin]).published.last
    new_version = Iqvoc::Xllabel.base_class.by_origin(params[:origin]).unpublished.last!

    authorize! :merge, new_version

    ActiveRecord::Base.transaction do
      new_version.publish

      if new_version.publishable?
        new_version.save
        begin
         # TODO if RdfStore.update(new_version.rdf_uri, label_url(:id => new_version, :format => :ttl))
         #   new_version.update_attribute(:rdf_updated_at, 1.seconds.since)
         # end
        rescue Exception => e
          handle_virtuoso_exception(e.message)
        end

        if current_label && !current_label.destroy
          flash[:error] = t('txt.controllers.versioning.merged_delete_error')
          redirect_to label_path(published: 0, id: new_version)
        end

        if new_version.has_concept_or_label_relations?
          flash[:success] = t('txt.controllers.versioning.published')
          redirect_to label_path(id: new_version)
        else
          flash[:error] = t('txt.controllers.versioning.published_with_warning')
          redirect_to label_path(id: new_version)
        end

      else
        flash[:error] = t('txt.controllers.versioning.merged_publishing_error')
        redirect_to label_path(published: 0, id: new_version)
      end
    end
  end

  def branch
    current_label = Iqvoc::Xllabel.base_class.by_origin(params[:origin]).published.last!

    if draft_label = Iqvoc::Xllabel.base_class.by_origin(params[:origin]).unpublished.last
      flash[:info] = t('txt.controllers.versioning.branch_error')
      redirect_to label_path(published: 0, id: draft_label)
    else
      authorize! :branch, current_label
      new_version = nil
      ActiveRecord::Base.transaction do
        new_version = current_label.branch
        new_version.save!
        Iqvoc.change_note_class.create! do |note|
          note.owner = new_version
          note.language = I18n.locale.to_s
          note.position = (current_label.send(Iqvoc.change_note_class_name.to_relation_name).maximum(:position) || 0).succ
          note.annotations_attributes = [
            { namespace: 'dct', predicate: 'creator', value: current_user.name },
            { namespace: 'dct', predicate: 'modified', value: DateTime.now.to_s }
          ]
        end
      end
      flash[:success] = t('txt.controllers.versioning.branched')
      redirect_to edit_label_path(published: 0, id: new_version, check_associations_in_editing_mode: true)
    end
  end

  def consistency_check
    label = Iqvoc::Xllabel.base_class.by_origin(params[:origin]).unpublished.last!

    authorize! :check_consistency, label

    if label.publishable?
      flash[:success] = t('txt.controllers.versioning.consistency_check_success')
      redirect_to label_path(published: 0, id: label)
    else
      flash[:error] = t('txt.controllers.versioning.consistency_check_error')
      redirect_to edit_label_path(published: 0, id: label, full_consistency_check: 1)
    end
  end

  def to_review
    label = Iqvoc::Xllabel.base_class.by_origin(params[:origin]).unpublished.last!

    authorize! :send_to_review, label

    if label.publishable?
      label.to_review

      label.save!
      flash[:success] = t('txt.controllers.versioning.to_review_success')
      redirect_to label_path(published: 0, id: label)
    else
      flash[:error] = t('txt.controllers.versioning.consistency_check_error')
      redirect_to edit_label_path(published: 0, id: label, full_consistency_check: 1)
    end
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action proc { |ctrl| (ctrl.action_has_layout = false) if ctrl.request.xhr? }

  def index
    authorize! :read, Iqvoc::Xllabel.base_class

    query_value = search_string(params.expect(:query), params[:mode])
    scope = Iqvoc::Xllabel.base_class
                          .editor_selectable
                          .by_query_value(query_value)

    if params[:language] # NB: this is not the same as :lang, which is supplied via route
      scope = scope.by_language(params[:language])
    end
    @labels = scope.order(Arel.sql("LENGTH(#{Iqvoc::Xllabel.base_class.table_name}.value)")).all

    respond_to do |format|
      format.html do
        redirect_to action: 'index', format: 'txt', **params.permit(:query, :mode)
      end
      format.text do
        render plain: @labels.map { |label| "#{label.origin}: #{label.value}" }.join("\n")
      end
      format.json do
        response = []
        # group labels to avoid duplicates
        # FIXME: filter in SQL directly
        @labels.group_by { |l| l.origin }.each { |origin, labels|
          response << label_widget_data(labels.first)
        }

        render json: response
      end
    end
  end

  def show
    scope = Iqvoc::Xllabel.base_class.by_origin(params[:id]).with_associations

    @published = params[:published] == '1' || !params[:published]
    if @published
      scope = scope.published
      @new_label_version = Iqvoc::Xllabel.base_class.by_origin(params[:id]).unpublished.last
    else
      scope = scope.unpublished
    end

    @label = scope.last!

    authorize! :read, @label

    respond_to do |format|
      format.html do
        @published ? render('show_published') : render('show_unpublished')
      end
      format.any(:rdf, :ttl, :nt)
    end
  end

  def new
    authorize! :create, Iqvoc::Xllabel.base_class
    @label = Iqvoc::Xllabel.base_class.new
    @label.build_initial_change_note(current_user)
    @label.build_notes
  end

  def create
    authorize! :create, Iqvoc::Xllabel.base_class

    @label = Iqvoc::Xllabel.base_class.new(label_params)

    if @label.valid?
      if @label.save
        flash[:success] = I18n.t('txt.controllers.versioned_label.success')
        redirect_to label_path(published: 0, id: @label.origin)
      else
        flash.now[:error] = I18n.t('txt.controllers.versioned_label.error')
        render :new
      end
    else
      flash.now[:error] = I18n.t('txt.controllers.versioned_label.error')
      render :new
    end
  end

  def edit
    @label = Iqvoc::Xllabel.base_class.by_origin(params[:id]).unpublished.last!
    authorize! :update, @label

    if params[:check_associations_in_editing_mode]
      @association_objects_in_editing_mode = @label.associated_objects_in_editing_mode
    end

    # @pref_labelings = PrefLabeling.by_label(@label).all(:include => {:owner => :pref_labels}).sort
    # @alt_labelings = AltLabeling.by_label(@label).all(:include => {:owner => :pref_labels}).sort

    if params[:full_consistency_check]
      @label.publishable?
    end

    @label.build_notes
  end

  def update
    @label = Iqvoc::Xllabel.base_class.by_origin(params[:id]).unpublished.last!
    authorize! :update, @label

    # set to_review to false if someone edits a label
    label_params["to_review"] = "false"

    respond_to do |format|
      format.html do
        if @label.update(label_params)
          flash[:success] = I18n.t('txt.controllers.versioned_label.update_success')
          redirect_to label_path(published: 0, id: @label)
        else
          flash.now[:error] = I18n.t('txt.controllers.versioned_label.update_error')
          render action: :edit
        end
      end
    end
  end

  def destroy
    @new_label = Iqvoc::Xllabel.base_class.by_origin(params[:id]).unpublished.last!
    authorize! :destroy, @new_label

    if @new_label.destroy
      published_label = Iqvoc::Xllabel.base_class.published.by_origin(@new_label.origin).first
      flash[:success] = I18n.t('txt.controllers.label_versions.delete')
      redirect_to published_label.present? ? label_path(id: published_label.origin) : dashboard_path
    else
      flash[:error] = I18n.t('txt.controllers.label_versions.delete_error')
      redirect_to label_path(published: 0, id: @new_label)
    end
  end

  def duplicate
    authorize! :create, Iqvoc::Xllabel.base_class
    label = Iqvoc::Xllabel.base_class.by_origin(params[:origin]).published.first
    if Iqvoc::Xllabel.base_class.by_origin(params[:origin]).unpublished.last
      flash[:error] = t('txt.controllers.label.duplicate_error')
      redirect_to label_path(published: 1, id: label)
    end

    @new_label = label.duplicate(current_user)
    @new_label.build_notes
  end

  def new_from_concept
    authorize! :create, Iqvoc::Xllabel.base_class
    @label = Iqvoc::Xllabel.base_class.new

    respond_to do |format|
      format.html do
        render layout: false
      end
    end
  end

  def create_from_concept
    authorize! :create, Iqvoc::Xllabel.base_class

    @label = Iqvoc::Xllabel.base_class.new(label_params)
    @label.build_initial_change_note(current_user)

    if @label.save
      #TODO: idea for solving this
      #flash[:success] = I18n.t('txt.controllers.versioned_label.success')
      head :created
    else
      #TODO: idea for solving this
      #flash.now[:error] = I18n.t('txt.controllers.versioned_label.error')
      head :bad_request
    end
  end

  private

  def label_params
    params.require(:label).permit!
  end

  def search_string(query, mode = 'contains')
    input = query&.strip

    if mode == 'exact_match'
      "#{input}"
    elsif mode == 'begins'
      "#{input}%"
    else
      "%#{input}%"
    end
  end
end

app/helpers/labels_helper.rb
# frozen_string_literal: false

module LabelsHelper
  def render_label_rdf(document, label)
    document << label.build_rdf_subject do |c|

      c.Schema::expires(label.expired_at.to_s) if label.expired_at

      c.Owl::deprecated(true) if label.expired?

      c.Skosxl::literalForm(label.value, lang: label.language)

      label.relations.each do |relation|
        relation.build_rdf(document, c)
      end

      if Iqvoc::rdf_show_change_notes
        label.notes.each do |note|
          note.build_rdf(document, c)
        end
      end

      Iqvoc::Xllabel.additional_association_class_names.keys.each do |class_name|
        label.send(class_name.to_relation_name).each do |additional_object|
          additional_object.build_rdf(document, c)
        end
      end
    end
  end

  def render_label_association(hash, label, association_class, further_options = {})
    return unless association_class.partial_name(label)
    ((hash[association_class.view_section(label)] ||= {})[association_class.view_section_sort_key(label)] ||= '') <<
      render(association_class.partial_name(label), further_options.merge(label: label, klass: association_class))
  end

  def label_view_data(label)
    res = {'main' => {}}

    res['main'][10] = render 'labels/language', label: label

    res['main'][400] = render 'labels/details', label: label

    Iqvoc::Concept.labeling_classes.keys.each do |labeling_class|
      render_label_association(res, label, labeling_class)
    end

    Iqvoc::Xllabel.relation_classes.each do |relation_class|
      render_label_association(res, label, relation_class)
    end

    Iqvoc::Xllabel.note_classes.each do |note_class|
      render_label_association(res, label, note_class)
    end

    Iqvoc::Xllabel.additional_association_classes.keys.each do |assoc_class|
      render_label_association(res, label, assoc_class)
    end

    res
  end

  def label_header(label)
    desc = label.class.model_name.human

    if label.expired_at
      desc += " #{t('txt.views.concepts.expired_at', date: l(label.expired_at, format: :long))} "
    end

    title = label.value .present? ? label.value : label.origin

    page_header title: title.to_s, desc: desc.html_safe
  end
end

app/views/labels/_base_data.html.erb
<h3><%= Label::Base.model_name.human %></h3>

<%= form_for @label, :as => 'label', :url => @label.new_record? ? labels_path : label_path(:id => @label, :published => 0), :html => {:class => "form"} do |f| %>
  <fieldset id="label_base_data">
    <legend><%= t("txt.common.attributes") %></legend>
    <ol>
      <li>
        <label><%= t("txt.views.labels.template_form") %></label>
        <%= f.text_field :value %>
      </li>
      <li>
        <%= f.label :language %>
        <%= @label.language %>
        <%= f.hidden_field :language %>
      </li>

      <%- if Iqvoc::XLLabel.has_additional_base_data -%>
        <%= render :partial => 'partials/label/additional_base_data', :locals => { :f => f } %>
      <%- end -%>

      <li>
        <%= f.label :follow_up %>
        <%= f.text_field :follow_up, :class => "datepicker" %>
      </li>
      <li>
        <%= f.label :expired_at %>
        <%= f.text_field :expired_at, :class => "datepicker" %>
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <legend>Relations</legend>
    <ol>
      <%- Iqvoc::XLLabel.relation_classes.each do |relation_class| -%>
        <%= render relation_class.edit_partial_name(@label), :label => @label, :klass => relation_class %>
      <%- end -%>
    </ol>
  </fieldset>

  <%- Iqvoc::XLLabel.additional_association_classes.keys.each do |association_class| -%>
    <fieldset>
      <legend><%= association_class.model_name.human(:count => 2) %></legend>
      <ol>
        <%= render association_class.edit_partial_name(@label), :label => @label, :klass => association_class, :f => f %>
      </ol>
    </fieldset>
  <%- end -%>


  <% unless @label.new_record? %>
    <% Iqvoc::XLLabel.note_classes.each do |note_class| %>
      <%= render note_class.edit_partial_name(@label), :owner_klass => @label, :assoc_klass => note_class, :f => f %>
    <% end %>
  <% end %>

  <%= f.submit t("txt.common.save") %>

  <% unless controller.action_name == "new" || controller.action_name == "create" %>
    <%= link_to t("txt.common.reset"), nil, :class => "button" %>
  <% end %>
<% end %>

app/views/labels/_details.html.erb
<%- if label.expired_at -%>
  <h4><%= t("txt.views.labels.expired_at") %></h4>
  <div class="relation">
    <%= l(label.expired_at)%>
  </div>
<%- end -%>

app/views/labels/_form.html.erb
<%= bootstrap_form_for label,
  :as => :label,
  :url => label.new_record? ? labels_path : label_path(:id => label, :published => 0),
  :layout => :horizontal do |f| %>

  <fieldset id="label_base_data">
    <legend><%= t("txt.common.attributes") %></legend>
    <%= f.text_field :value,
                     autofocus: true,
                     autocomplete: 'off',
                     data: {
                       'query-url': labels_path(:format => :json),
                       'entity-uri' => label_path(:id => '{id}'),
                       'duplicate-message': t("txt.common.duplicate_labels"),
                       'duplicate-check-mode': Iqvoc.config['label_duplicate_check_mode'] || 'exact_match',
                     } %>

    <%= f.select :language, Iqvoc.all_languages %>

    <% if Iqvoc::Xllabel.has_additional_base_data %>
      <%= render 'partials/label/additional_base_data', :f => f %>
    <% end %>

    <%= f.text_field :follow_up, :class => 'datepicker' %>
    <%= f.text_field :expired_at, :class => 'datepicker' %>
  </fieldset>

  <% if Iqvoc::Xllabel.relation_classes.any? %>
  <fieldset>
    <legend><%= Label::Relation::Skosxl::Base.model_name.human(:count => 2) %></legend>
      <% Iqvoc::Xllabel.relation_classes.each do |relation_class| %>
        <%= render relation_class.edit_partial_name(label), :f => f, :label => label, :klass => relation_class %>
      <% end %>
  </fieldset>
  <% end %>

  <% Iqvoc::Xllabel.additional_association_classes.keys.each do |association_class| %>
    <fieldset>
      <legend><%= association_class.model_name.human(:count => 2) %></legend>
      <%= render association_class.edit_partial_name(label), :label => label, :klass => association_class, :f => f %>
    </fieldset>
  <% end %>


  <% Iqvoc::Xllabel.note_classes.each do |note_class| %>
    <% unless note_class.edit_partial_name(label).nil? %>
      <%= render note_class.edit_partial_name(label), :owner_klass => label, :assoc_klass => note_class, :f => f %>
    <% end %>
  <% end %>

  <hr />

  <div class="mb-5">
    <%= f.submit t("txt.common.save"), :class => 'btn btn-primary' %>
    <%= link_to t("txt.common.cancel"), label.new_record? ? dashboard_path : label_path(:id => label, :published => 0), :class => "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/labels/_header.html.erb
<% published_param = label.published? ? nil : 0 %>
<%= content_for :head do %>
  <link href="<%= rdf_url(label.origin, :format => :ttl, :published => published_param, :lang => nil) %>" type="text/turtle" rel="alternate" title=""/>
  <link href="<%= rdf_url(label.origin, :format => :rdf, :published => published_param, :lang => nil) %>" type="application/rdf+xml" rel="alternate" title=""/>
<% end %>

<%= label_header(label) %>

app/views/labels/_language.html.erb
<div class="panel">
  <h2><%= t("txt.views.labels.language") %></h2>
  <%= label.language %>
</div>

app/views/labels/_show_head.html.erb
<%- published_param = @label.published? ? nil : 0 %>
<%= content_for :head do -%>
  <link href="<%= rdf_url(@label.origin, :format => :ttl, :published => published_param, :lang => nil) %>" type="text/turtle" rel="alternate" title=""/>
  <link href="<%= rdf_url(@label.origin, :format => :rdf, :published => published_param, :lang => nil) %>" type="application/rdf+xml" rel="alternate" title=""/>
<% end -%>

<h2><%= @label.class.model_name.human %>:
  <%= @label.origin %>
  <%- if !@label.published? %>
    (<%= t('txt.common.unpublished_version') %>)
  <%- end -%>
</h2>

<div id="abstract_uri">
  <%= rdf_url(@label.origin, :format => nil, :published => published_param, :lang => nil) %>
  (<%= link_to "Turtle", rdf_url(@label.origin, :format => :ttl, :published => published_param, :lang => nil) %>,
  <%= link_to "RDF/XML", rdf_url(@label.origin, :format => :rdf, :published => published_param, :lang => nil) %>)
</div>

<%- if @label.expired_at -%>
  <h4><%= t('txt.views.concepts.expired_at', :date => l(@label.expired_at, :format => :long)) %></h4>
<%- end -%>

app/views/labels/_sidebar.html.erb
<% published_param = label.published? ? nil : 0 %>

<%= sidebar do %>
  <% unless label.new_record? %>
    <%= sidebar_header t('txt.common.representations') %>
    <%= sidebar_item :icon => 'share', :text => 'HTML', :path => rdf_url(label.origin, :format => :html, :published => published_param, :lang => nil) %>
    <%= sidebar_item :icon => 'share', :text => 'RDF/XML', :path => rdf_url(label.origin, :format => :rdf, :published => published_param, :lang => nil), :id => 'rdf_link_xml' %>
    <%= sidebar_item :icon => 'share', :text => 'RDF/Turtle', :path => rdf_url(label.origin, :format => :ttl, :published => published_param, :lang => nil), :id => 'rdf_link_ttl' %>
    <%= sidebar_item :icon => 'share', :text => 'RDF/NTriples', :path => rdf_url(label.origin, :format => :nt, :published => published_param, :lang => nil), :id => 'rdf_link_nt' %>
  <% end %>

  <%= sidebar_header 'Links' %>
  <% unless label.new_record? %>
    <%= sidebar_item :icon => 'link', :text => t('txt.models.label.uri'), :path => rdf_url(label.origin, :format => nil, :published => published_param, :lang => nil) %>
  <% end %>
  <% Iqvoc.first_level_classes.each do |klass| %>
    <%= sidebar_item { render(klass.new_link_partial_name) } %>
  <% end %>
<% end %>

app/views/labels/duplicate.html.erb
<%= page_header :title => t("txt.views.labels.new") %>

<%= error_messages_for @new_label %>
<%= render 'form', :label => @new_label %>

app/views/labels/edit.html.erb
<%= render 'header', :label => @label %>
<%= render 'sidebar', :label => @label %>

<%= error_messages_for @label %>

<%= render 'labels/notifications/referenced_labels',
  :association_objects_in_editing_mode => @association_objects_in_editing_mode %>

<%= render 'form', :label => @label %>

app/views/labels/new.html.erb
<%= page_header :title => t("txt.views.labels.new") %>

<%= error_messages_for @label %>
<%= render 'form', :label => @label %>
<%= render 'sidebar', :label => @label %>

app/views/labels/new_from_concept.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title"><%= t("txt.views.labels.new") %></h1>
    </div>
    <%= bootstrap_form_for @label,
      :as => :label,
      :url => concept_create_label_path,
      :layout => :horizontal, remote: true do |f| %>
      <div class="modal-body">
        <fieldset id="label_base_data">
          <legend><%= t("txt.common.attributes") %></legend>
          <%= f.text_field :value %>

          <%= f.select :language, Iqvoc.all_languages %>
        </fieldset>
      </div>

      <div class="modal-footer">
        <%= f.submit t("txt.common.save"), :class => 'btn btn-primary', onclick: "$('#concept-teaser-modal').modal('hide');" %>
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal"><%= t("txt.common.cancel") %></button>
      </div>
    <% end %>
  </div>
</div>

app/views/labels/show_published.html.erb
<%= render 'header', :label => @label %>
<%= render 'sidebar', :label => @label %>

<% if can?(:read, @new_label_version) || can?(:branch, @label) %>
  <div class="editing_versioning_toolbar">
    <% if @new_label_version.blank? && can?(:branch, @label) %>
      <%= button_to t("txt.views.versioning.versioning_mode"),
      label_versions_branch_path(:origin => @label.origin), :class => 'btn btn-outline-secondary' %>
      <%= link_to t("txt.views.versioning.duplicate"),
      label_duplicate_path(origin: @label.origin), :class => 'btn btn-outline-secondary' %>
    <% elsif can?(:read, @new_label_version) %>
      <%= link_to t("txt.views.versioning.preview_new_version"),
      label_path(:published => 0, :id => @new_label_version), :class => 'btn btn-outline-secondary' %>
    <% end %>
  </div>
<% end %>

<%= render 'layouts/sections', :sections => Iqvoc::Xllabel.view_sections, :data => label_view_data(@label) %>

app/views/labels/show_unpublished.html.erb
<%= render 'header', :label => @label %>
<%= render 'sidebar', :label => @label %>

<%= alert :info, :header => t('txt.common.unpublished_version') + "." do %>
  <%= t("txt.views.versioning.current_revision", :rev => @label.rev) %>
<% end %>

<div class="editing_versioning_toolbar">
  <% if can?(:merge, @label) %>
    <%= button_to t("txt.views.versioning.publishing"),
                  label_versions_merge_path(:origin => @label.origin), :class => 'btn btn-primary' %>
  <% end %>

  <% if can?(:check_consistency, @label) %>
    <%= button_to t("txt.views.versioning.consistency_check"),
      label_versions_consistency_check_path(:origin => @label.origin),
      :method => :get, :class => 'btn btn-outline-secondary' %>
  <% end %>

  <% if can?(:send_to_review, @label) %>
    <%= button_to t("txt.common.to_review"),
    label_versions_to_review_path(:origin => @label.origin),
    :class => 'btn btn-outline-secondary' %>
  <% end %>

  <% if can?(:update, @label) %>
    <%= link_to t("txt.views.versioning.edit_mode"),
                edit_label_path(:published => 0, :id => @label.origin),
                :class => 'btn btn-outline-secondary'  %>
  <% end %>

  <% if can?(:destroy, @label) %>
    <%= button_to delete_button_text(@label),
      label_path(:published => 0, :id => @label.origin),
      :method => :delete,
      :confirm => I18n.t("txt.views.versioning.delete_confirm"),
      :class => 'btn btn-danger' %>
  <% end %>
</div>

<%= render 'layouts/sections', :sections => Iqvoc::Xllabel.view_sections, :data => label_view_data(@label) %>